/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  about: () => import("@/views/about/index.vue"),
  game_community: () => import("@/views/game/community/index.vue"),
  game_game: () => import("@/views/game/game/index.vue"),
  game_live: () => import("@/views/game/live/index.vue"),
  game_map: () => import("@/views/game/map/index.vue"),
  game_mode: () => import("@/views/game/mode/index.vue"),
  game_server: () => import("@/views/game/server/index.vue"),
  home: () => import("@/views/home/index.vue"),
  manage_dict: () => import("@/views/manage/dict/index.vue"),
  manage_menu: () => import("@/views/manage/menu/index.vue"),
  manage_role: () => import("@/views/manage/role/index.vue"),
  "manage_user-detail": () => import("@/views/manage/user-detail/[id].vue"),
  manage_user: () => import("@/views/manage/user/index.vue"),
  monitor_cache: () => import("@/views/monitor/cache/index.vue"),
  monitor_logs_error: () => import("@/views/monitor/logs_error/index.vue"),
  monitor_logs_file: () => import("@/views/monitor/logs_file/index.vue"),
  monitor_logs_login: () => import("@/views/monitor/logs_login/index.vue"),
  monitor_logs_operation: () => import("@/views/monitor/logs_operation/index.vue"),
  monitor_logs_scheduler: () => import("@/views/monitor/logs_scheduler/index.vue"),
  monitor_scheduler: () => import("@/views/monitor/scheduler/index.vue"),
  monitor_system: () => import("@/views/monitor/system/index.vue"),
  server_csgo: () => import("@/views/server/csgo/index.vue"),
  "user-center": () => import("@/views/user-center/index.vue"),
};
