/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'about',
    path: '/about',
    component: 'layout.base$view.about',
    meta: {
      title: 'about',
      i18nKey: 'route.about',
      icon: 'fluent:book-information-24-regular',
      order: 10
    }
  },
  {
    name: 'game',
    path: '/game',
    component: 'layout.base',
    meta: {
      title: 'game',
      i18nKey: 'route.game'
    },
    children: [
      {
        name: 'game_community',
        path: '/game/community',
        component: 'view.game_community',
        meta: {
          title: 'game_community',
          i18nKey: 'route.game_community'
        }
      },
      {
        name: 'game_game',
        path: '/game/game',
        component: 'view.game_game',
        meta: {
          title: 'game_game',
          i18nKey: 'route.game_game'
        }
      },
      {
        name: 'game_mode',
        path: '/game/mode',
        component: 'view.game_mode',
        meta: {
          title: 'game_mode',
          i18nKey: 'route.game_mode'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: 'manage',
      i18nKey: 'route.manage',
      icon: 'carbon:cloud-service-management',
      order: 9,
      roles: ['R_ADMIN']
    },
    children: [
      {
        name: 'manage_dict',
        path: '/manage/dict',
        component: 'view.manage_dict',
        meta: {
          title: 'manage_dict',
          i18nKey: 'route.manage_dict'
        }
      },
      {
        name: 'manage_menu',
        path: '/manage/menu',
        component: 'view.manage_menu',
        meta: {
          title: 'manage_menu',
          i18nKey: 'route.manage_menu',
          icon: 'material-symbols:route',
          order: 3,
          roles: ['R_ADMIN'],
          keepAlive: true
        }
      },
      {
        name: 'manage_role',
        path: '/manage/role',
        component: 'view.manage_role',
        meta: {
          title: 'manage_role',
          i18nKey: 'route.manage_role',
          icon: 'carbon:user-role',
          order: 2,
          roles: ['R_SUPER']
        }
      },
      {
        name: 'manage_user',
        path: '/manage/user',
        component: 'view.manage_user',
        meta: {
          title: 'manage_user',
          i18nKey: 'route.manage_user',
          icon: 'ic:round-manage-accounts',
          order: 1,
          roles: ['R_ADMIN']
        }
      },
      {
        name: 'manage_user-detail',
        path: '/manage/user-detail/:id',
        component: 'view.manage_user-detail',
        props: true,
        meta: {
          title: 'manage_user-detail',
          i18nKey: 'route.manage_user-detail',
          hideInMenu: true,
          roles: ['R_ADMIN'],
          activeMenu: 'manage_user'
        }
      }
    ]
  },
  {
    name: 'monitor',
    path: '/monitor',
    component: 'layout.base',
    meta: {
      title: 'monitor',
      i18nKey: 'route.monitor'
    },
    children: [
      {
        name: 'monitor_cache',
        path: '/monitor/cache',
        component: 'view.monitor_cache',
        meta: {
          title: 'monitor_cache',
          i18nKey: 'route.monitor_cache'
        }
      },
      {
        name: 'monitor_logs',
        path: '/monitor/logs',
        meta: {
          title: 'monitor_logs',
          i18nKey: 'route.monitor_logs'
        },
        children: [
          {
            name: 'monitor_logs_error',
            path: '/monitor/logs/error',
            component: 'view.monitor_logs_error',
            meta: {
              title: 'monitor_logs_error',
              i18nKey: 'route.monitor_logs_error'
            }
          },
          {
            name: 'monitor_logs_file',
            path: '/monitor/logs/file',
            component: 'view.monitor_logs_file',
            meta: {
              title: 'monitor_logs_file',
              i18nKey: 'route.monitor_logs_file'
            }
          },
          {
            name: 'monitor_logs_login',
            path: '/monitor/logs/login',
            component: 'view.monitor_logs_login',
            meta: {
              title: 'monitor_logs_login',
              i18nKey: 'route.monitor_logs_login'
            }
          },
          {
            name: 'monitor_logs_operation',
            path: '/monitor/logs/operation',
            component: 'view.monitor_logs_operation',
            meta: {
              title: 'monitor_logs_operation',
              i18nKey: 'route.monitor_logs_operation'
            }
          },
          {
            name: 'monitor_logs_scheduler',
            path: '/monitor/logs/scheduler',
            component: 'view.monitor_logs_scheduler',
            meta: {
              title: 'monitor_logs_scheduler',
              i18nKey: 'route.monitor_logs_scheduler'
            }
          }
        ]
      },
      {
        name: 'monitor_scheduler',
        path: '/monitor/scheduler',
        component: 'view.monitor_scheduler',
        meta: {
          title: 'monitor_scheduler',
          i18nKey: 'route.monitor_scheduler'
        }
      },
      {
        name: 'monitor_system',
        path: '/monitor/system',
        component: 'view.monitor_system',
        meta: {
          title: 'monitor_system',
          i18nKey: 'route.monitor_system'
        }
      }
    ]
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center',
      hideInMenu: true
    }
  }
];
